FROM alpine/helm:3.15.4

RUN apk add --no-cache curl bash

ENV KUBECTL_VERSION="v1.27.1"
RUN curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl" && \
    chmod +x ./kubectl && \
    mv ./kubectl /usr/local/bin/kubectl

ENTRYPOINT ["/bin/bash"]
